name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.16
    - name: Install dependencies
      run: |
        make install

    - name: check lint
      run: |
        make lint

    - name: testing
      run: |
        make test
